### ISSUE TITLE
html_strip fails with attribute=">"

### ISSUE THREAD

**Issue by mlanett** [zaro/node-htmlstrip-native#10]
This example from github.com/azer/strip applies to this project as well:

var text = '<a data-sign=">">var text = 'Hello</a>';
Strip.html_strip(text, { include_script: false, include_style: false, compact_whitespace: true });
</a>';
html_strip(text, { include_script: false, include_style: false, compact_whitespace: true });

'"Hello '

**Comment by mlanett** [comment]
Strip = require("htmlstrip-native");
    var text = '<a data-sign=">"> Hello</a>';
    Strip.html_strip(text, { include_script: false, include_style: false, compact_whitespace: true });

Produces: ```"Hello ```

**Comment by zaro** [comment]
Yeah, attribute values were not processed correctly :)

Thanks for reporting this, fixed in master and 0.1.1.
