### ISSUE TITLE
html_strip fails depending on contents of comments

### ISSUE THREAD

**Issue by mlanett** [zaro/node-htmlstrip-native#11]
Simple comments seem to work but other common ones don't quite.

var text = ' Hello';
Strip.html_strip(text, { include_script: false, include_style: false, compact_whitespace: true });

// produces: '-- Hello'

**Comment by mlanett** [comment]
Damnit.

    var text = ' Hello';
    Strip.html_strip(text, { include_script: false, include_style: false, compact_whitespace: true });

produces '-- Hello'

**Comment by zaro** [comment]
Tags in comments didn't quite work , thanks for reporting :)

Fixed in master and 0.1.1.
