### ISSUE TITLE
Should have option to keep paragraph-level distinction

### ISSUE THREAD

**Issue by mlanett** [zaro/node-htmlstrip-native#12]
The library doesn't convert br or p into newlines, nor does it insert newlines between divs. Thus when importing html text, one loses all distinction between paragraphs. Any plans to add this, or should I do it and make a PR?

**Comment by zaro** [comment]
Well I don't actively use the library anymore, I am making just some small fixes now and then. So no plans, to add it. But if you make it I will definitely merge the PR.
