### ISSUE TITLE
Strange behaviour of `include_attributes` option, when set to `false`

### ISSUE THREAD

**Issue by hooke** [zaro/node-htmlstrip-native#14]
I've installed this module with version: "0.1.1" using npm.

include_attributes option behaves in some strange way:

if I use the following options:

```javascript
var options = {
 include_script : false,
 include_style : false,
 compact_whitespace : true,
 include_attributes : {
   'alt': false
    }
  };
```

html text like 
```javascript
var html = '<style>b {color: red;}</style>' +
' Yey, <b> No more,&nbsp;tags&amp;</b>' +
    '<img source="1.png" alt="smiley">';
```

is stripped down to `Yey, No more, tags& smiley` - but I will get the same result  if  set `'alt'` to `true`!

so, if I want to strip down alt attribute, I have to remove `include_attributes` option at all, or use like  this: ` include_attributes : { }`,
so abovementioned html text is correctly stripped to `Yey, No more, tags&`

**Comment by zaro** [comment]
Yeah, the value was not used at all, the presense of the key was used as flag to include the tag.
Fixed in 0.1.3
