### ISSUE TITLE
What is crash.js and why is it making GET requests to 8GOOD.ru?

### ISSUE THREAD

**Issue by JustinBeaudry** [zaro/node-htmlstrip-native#19]

**Comment by zaro** [comment]
I guess, I should delete it.
This is no part of the module itself, but rather a testcase for some HTML that used to crash the module.

The module is implemented in C++ only, and the only javacript used in it, is index.js.

**Comment by zaro** [comment]
fixed in 0.1.4

**Comment by JustinBeaudry** [comment]
I noticed that as well, it's just unnerving seeing external requests being made like that. Thanks for the cleanup.
