### ISSUE TITLE
Crash nodejs process while trying delete html tags

### ISSUE THREAD

**Issue by Areks** [zaro/node-htmlstrip-native#8]
I tried to use module for clearing html page from tags. I use this module for gettting html  https://github.com/request/request and then try to decode it and send to html_strip, but sometimes when i got wrong result after decoding html from buffer html_strip just crash the process. 
Test case
```
var
    request = require("request"),
    iconv = require('iconv-lite'),
    html_strip = require('htmlstrip-native');

request({
    uri: "http://8GOOD.RU/",
    method: "GET",
    timeout: 10000,
    followRedirect: false,
    encoding: null,
    maxRedirects: 1,
    headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'
    }
}, function(a, b, htmlBuffer) {

    console.log(htmlBuffer.length)

    var string = html_strip.html_strip(iconv.decode(htmlBuffer, 'utf-8'), {
        include_script : false,
        include_style : false,
        compact_whitespace : true
    });
    
    console.log(string)
})
```
I think better add global try/catch and if we got something strange just throw any exception that we can handle in node

**Comment by zaro** [comment]
Please add also some error logs to the issue.

I just tried this :  curl -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36' -v http://8good.ru/

It also prints some binary blob, which doesn't seem like text at all. The module expects only valid UTF16 strings in the buffer, and the result of iconv.decode(htmlBuffer, 'utf-8') is NOT a string, looks like binary blob.

So most probably this is not an isse with the module itself, but if you provide some error logs, I guess I can check further.

**Comment by Areks** [comment]
I haven't any logs, my process jusr crush. Yep my friend, you are right, this is not valid utf16 string with html. But the problem is that your module just crush with whole process.
Sometimes we don't know what data we have and we can get wrong input from different places, so i think you should add something like "try catch" and throw any exceptions like "Incorrect input data" that can be catched in application and programmer decide what to do. Just crush process without any information i think bad behavior in any case.

How do u think could it be implementing?

**Comment by zaro** [comment]
:) ok, now..  here is the thing. I tested your script, and on my machine it
doesn't crash ..
It exits correctly. If you can provide test case that crashes it, then I
guess I can have another look.

There are no exceptions in the C++ code, so there is no need fro try/catch
there.

**Comment by zaro** [comment]
If you can make a test script that crashes, so I can trace the actual problem just reopen the ticket.
