### ISSUE TITLE
html_strip with compact whitespace always removes last character

### ISSUE THREAD

**Issue by blaketarter** [zaro/node-htmlstrip-native#9]
I've noticed that when using `htmlstrip.html_strip()` with the `compact_whitespace` option set to true the last character is always removed because a single whitespace is inserted at the beginning. I don't really know C++ but poked around some and noticed that in `htmlstrip.cpp` at line `279` a whitespace is being added at the beginning of the buffer and never removed. Commenting out that line appeared to fix the issue but I'm sure breaks in some edge case.

**Comment by zaro** [comment]
yeah, there is a single whitespace character inserted in the beginning of the string, but that shouldn't cut off the last character. Can you provide a simple test case , to show when it gets cut ?

Inserting the space in the beginning was a hack and I should remove it I guess , anyway, but still it is interesting for me the scenario when the last char get cut off.

**Comment by zaro** [comment]
ok, fixed the hack in master branch. Can you test if the problem still persists ? and possible provide a test case ?

**Comment by blaketarter** [comment]
Just gave it a look and the problem looks fixed now! Also your test cases look like they cover everything I was doing! Thanks for the quick response.
